codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"  
  status:
    project:
      default:
        informational: true



comment:
  layout: "diff,flags,files"
  behavior: default
  require_changes: yes

ignore:
  - ".github/**/*"
  - "./*"
