codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

comment:
  layout: "diff,flags,files"
  behavior: default
  require_changes: yes

ignore:
  - ".github/**/*"
  - "./*"
