version: "3.8"
services:
  webapi:
    container_name: GirafRestApi
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: 'LocalDocker'
  db:
    container_name: GirafMysqlDatabase
    image: mysql
    restart: always
    ports:  
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'giraf'
      MYSQL_USER: 'local'
      MYSQL_PASSWORD: 'Giraf123'
      MYSQL_RANDOM_ROOT_PASSWORD: 1
volumes:
  db_data: