using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using GirafWebApi.Contexts;
using GirafWebApi.Models;
using IdentityServer4.Validation;
using IdentityServer4.Services;
using Microsoft.AspNetCore.Http;

using Microsoft.AspNetCore.Http;
using System.Linq;
using Microsoft.Extensions.FileProviders;
using Microsoft.Data.Sqlite;
using System.Xml.Linq;
using System.IO;
using System;
using Microsoft.EntityFrameworkCore;

namespace GirafWebApi
{
    /// <summary>
    /// The base-class for handling setup in the Giraf REST-api.
    /// </summary>
    public class Startup
    {
        
        GirafDbContext context;
        
        protected IHostingEnvironment _environment;

        /// <summary>
        /// Instantiates a new Startup-object for building the ASP.net REST server.
        /// </summary>
        /// <param name="env">A reference to the <see cref="IHostingEnvironment"/> interface, on which the server is build.</param>
        
        public Startup(IHostingEnvironment env)
        {
            _environment = env;
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        /// <summary>
        /// Auto generated by ASP.net. Stores configuration information for the server.
        /// </summary>
        /// <returns>The current configuration</returns>
        public IConfigurationRoot Configuration { get; }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services">The collection of services to add to the server.</param>
        public virtual void ConfigureServices(IServiceCollection services)
        {             
            services.AddIdentity<GirafUser, IdentityRole>(options => {
                options.Cookies.ApplicationCookie.LoginPath = new PathString("/api/values/");
            })
                .AddEntityFrameworkStores<GirafDbContext>()
                .AddDefaultTokenProviders();

            // Add framework services.
            services.AddMvc();
            // configure identity server with in-memory stores, keys, clients and resources
           
            services.AddIdentityServer()
                .AddInMemoryApiResources(Configurations.ApiResources.GetApiResources())
                .AddInMemoryClients(Configurations.Clients.GetClients())
                .AddTemporarySigningCredential(); // Skal måske ændres?

            services.AddAuthorization(options =>
            {
                options.AddPolicy("Admin",
                    policy => policy.RequireRole(context.Roles.Where(x => x.Name == "Admin").First().Name));
            });

            services.AddTransient<IResourceOwnerPasswordValidator, Configurations.ResourceOwnerPasswordValidator>();

            //Add the physical FileProvider for reading images on the server-side
            
            var physicalProvider = _environment.ContentRootFileProvider;
            services.AddSingleton<IFileProvider>(physicalProvider);
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        /// <param name="app"></param>
        /// <param name="env"></param>
        /// <param name="loggerFactory"></param>
        /// <param name="context"></param>
        public void Configure(IApplicationBuilder app,
            ILoggerFactory loggerFactory, GirafDbContext context)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            this.context = context;
            DBInitializer.Initialize(context);
            
            app.UseIdentity();
            app.UseIdentityServer();
            
            app.UseJwtBearerAuthentication();

            app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:5001",
                RequireHttpsMetadata = false,
                ApiName = "MyApi",
                AllowedScopes = { "MyApi"}
            });

            app.UseMvc();
        }
    }
}
