using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using GirafWebApi.Models;
using IdentityServer4.Validation;
using Microsoft.AspNetCore.Http;
using GirafWebApi.Extensions;

namespace GirafWebApi.Setup
{
    /// <summary>
    /// The base-class for handling setup in the Giraf REST-api.
    /// </summary>
    public class Startup
    {
        protected IHostingEnvironment _environment;

        /// <summary>
        /// Instantiates a new Startup-object for building the ASP.net REST server.
        /// </summary>
        /// <param name="env">A reference to the <see cref="IHostingEnvironment"/> interface, on which the server is build.</param>
        public Startup(IHostingEnvironment env)
        {
            _environment = env;
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        /// <summary>
        /// Auto generated by ASP.net. Stores configuration information for the server.
        /// </summary>
        /// <returns>The current configuration</returns>
        public IConfigurationRoot Configuration { get; }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services">The collection of services to add to the server.</param>
        public virtual void ConfigureServices(IServiceCollection services)
        {    
            services.AddIdentity<GirafUser, IdentityRole>(options => {
                options.Cookies.ApplicationCookie.LoginPath = new PathString("/api/values/");
            })
                .AddEntityFrameworkStores<GirafDbContext>()
                .AddDefaultTokenProviders();

            // Add framework services.
            services.AddMvc();
            // configure identity server with in-memory stores, keys, clients and resources
           
            services.AddIdentityServer()
                .AddInMemoryApiResources(GirafWebApi.IdentityServer.Configurations.ApiResources.GetApiResources())
                .AddInMemoryClients(GirafWebApi.IdentityServer.Configurations.Clients.GetClients())
                .AddTemporarySigningCredential(); // Skal måske ændres?

            services.AddAuthorization(options =>
            {
                options.AddPolicy("Admin", policy => policy.RequireRole("Admin"));
            });

            services.AddTransient<IResourceOwnerPasswordValidator, GirafWebApi.IdentityServer.Configurations.ResourceOwnerPasswordValidator>();

            //Add the database context to the server using extension-methods
            if(Program.DbOption == DbOption.SQLite) {
                services.AddSqlite();
            }
            else
                services.AddSql();     
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        /// <param name="app"></param>
        /// <param name="env"></param>
        /// <param name="loggerFactory"></param>
        /// <param name="context"></param>
        public void Configure(IApplicationBuilder app,
            ILoggerFactory loggerFactory, GirafDbContext context)
        {
            //Add some sample data if the application is running locally
            if(Program.DbOption == DbOption.SQLite) DBInitializer.Initialize(context);

            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            
            app.UseIdentity();
            app.UseIdentityServer();
            
            app.UseJwtBearerAuthentication();

            app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:5001",
                RequireHttpsMetadata = false,
                ApiName = "MyApi",
                AllowedScopes = { "MyApi"}
            });

            app.UseMvc();
        }
    }
}