on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: aau-giraf/web-api
          tag_with_ref: true
          push: false