name: Integration Test

on:
  pull_request:
    branches: ["develop", "Release"]
jobs:
  build:
    name: Integration Test
    runs-on: ${{ matrix.os }}
    env:
      ASPNETCORE_ENVIRONMENT: "CI"
    strategy:
      matrix:
        os: [ubuntu-20.04]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 'Giraf123'
          MYSQL_DATABASE: 'giraf'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up API
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
      - name: Run API
        # secrets are located in repo aau-giraf/web-api:settings.secrets
        # "nohup" is used to run the dotnet application in the background 
        run: |
          dotnet tool install --global dotnet-ef
          cd GirafRest
          dotnet restore
          dotnet-ef database update
          nohup dotnet run --sample-data > /dev/null 2>&1 &
      - name: Tests
        run: dotnet test ./GirafRest.IntegrationTest/
