name: Integration Test

on:
  push:

jobs:
  build:
    name: Integration Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up API
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      - name: Run API
        # secrets are located in repo aau-giraf/web-api:settings.secrets
        # "nohup" is used to run the dotnet application in the background 
        run: |
          export ASPNETCORE_ENVIRONMENT="Development"

      - name: Tests
        run: dotnet test ./GirafRest.IntegrationTest/
