name: Integration test

on: push
#  pull_request:
#    types: [ready_for_review, review_requested, opened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.201' ]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Giraf123
          MYSQL_DATABASE: 'giraf'
        ports:
          - 5000:5000
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - name: Set up API
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run API
        run: |
          ls /usr/share/fonts/truetype/dejavu
          mysql --host 127.0.0.1 --port 3306 -uroot -pGiraf123 -e "SHOW DATABASES"
          export ASPNETCORE_ENVIRONMENT="Production"
          bash scripts/ci-setup.sh ${{ env.IP }} ${{ secrets.IntegrationTestUser }} ${{ secrets.IntegrationTestPassword }}
          dotnet tool install --global dotnet-ef
          cd GirafRest
          dotnet restore
          dotnet ef database update
          nohup dotnet run --sample-data > /dev/null 2>&1 &
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r GirafIntegrationTest/requirements.txt
          python scripts/pictogen.py 6 pictograms
      - name: Test
        run: python GirafIntegrationTest/test.py