name: Unit Test

on:
  push:
jobs:
  build:
    name: Unit Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
